### ISSUE TITLE
프론트와 백엔드 연동 구조에 대한 논의

### ISSUE THREAD

**Issue by wesky93** [python-study-ko/devlog#2]
1. 백엔드는 graphql로만 구성하고 프론트는 s3로 단독 호스팅
2. 백엔드와 프론트는 graphql로 연동  하지만 프론트엔드는 백엔드를 통해 호스팅됨
3. 초기에는 백엔드에서 단순 html을 생성하여 운영하다 추후 프론트를 분리

위 3가지에 어떤식으로 개발하면 좋을지 논의하면 좋을거 같습니다.

**Comment by wesky93** [comment]
@MaseKor 의견좀

**Comment by MaseKor** [comment]
1

**Comment by wesky93** [comment]
그럼 프론트는 단독 호스팅 하는것으로 ㅋㅋ 마무리하겠습니다
